server:
  port:8080
spring:
datasource:
  url: jdbc:mysql://host:port/testdb1?useSSL=false&useUnicode=yes&characterEncoding=UTF-8
  driverClassName: com.mysql.jdbc.Driver
  username: sa
  password:
h2:
  console:
  enabled: true
jpa:
  spring.jpa.database-platform: org.hibernate.dialect.MySQLDialect
  hibernate:
  ddl-auto: update
  show-sql: true

